version: '3.9'

services:
  geospatial_api:
    container_name: geospatial_api
    image: geospatial_api
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@geospatial_db:5432/postgres
    depends_on:
      - geospatial_db
  
  geospatial_db:
    container_name: geospatial_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}